# -*- coding: utf-8 -*-
"""DBSCAN Clustering on Moon-Shaped Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1232xjG3Lst3qYvLUWdKCOwMVpyi1PxFu
"""

import numpy as np
import pandas as pd
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

x, y = make_moons(n_samples=300, noise=0.1)
data = pd.DataFrame(x, columns=['Feature 1', 'Feature 2'])

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

dbscan = DBSCAN(eps=0.3, min_samples = 5)
data['Cluster'] = dbscan.fit_predict(scaled_data)

plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='Feature 1', y='Feature 2', hue='Cluster', palette='viridis', s=100)
plt.title('DBSCAN Clustering')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend(title='Cluster')
plt.show()