# -*- coding: utf-8 -*-
"""Spam Detection System-Naive Bayes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKeArCF5i3FOr3M-WCz4e1g4s5od3QTd
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

data = pd.read_excel('Data.xlsx')
x = data['Text']
y =  data['Is_Spam']
data

vectorizer = CountVectorizer()
x_vectorized = vectorizer.fit_transform(x)

print("Features in training data:", vectorizer.get_feature_names_out())

X_train, X_test, Y_train, Y_test = train_test_split(x_vectorized, y, test_size=0.2)

NB = MultinomialNB()
NB.fit(X_train, Y_train)

pred = NB.predict(X_test)
print(pred)
print("Accuracy: ", accuracy_score(Y_test, pred))
print("Classification Report:\n", classification_report(Y_test, pred))

new_unseen_data = [
    "Congratulations! You've won a $1000 gift card!",
    "Good morning, I am Shehab call me?"
]
text = vectorizer.transform(new_unseen_data)

prediction = NB.predict(text)

for i in prediction:
  if i == 1:
    print("It is Spam")
  else:
     print("It is Ham")